service_name = 'twitter'
consumer_key = 'lX9NA48LLsK7CTpLZjpzg'
consumer_secret = 'VYcF4h6uLQ8wnxELuYhoWsX8mUlYfonqrTFoDVy8JA'
request_token_url='https://api.twitter.com/oauth/request_token'
access_token_url='https://api.twitter.com/oauth/access_token'
authorize_url='https://api.twitter.com/oauth/authorize'
base_url='https://api.twitter.com/1.1/'
